### ISSUE TITLE
Giving up connect / KeyError: 'refreshToken

### ISSUE THREAD

**Issue by steuerzentrale** [Sholofly/lghorizon#110] opened 2024-02-16 11:55 UTC
**Describe the bug**
The integration seemed to stopped working (UPC/Sunrise Switzerland), I dont get any status-updates anymore. I deleted the integration from HACS and reinstalled it again. I cannot get the integration to work, please see the log below. Maybe something changed at the providers backend.

environment
Core 2024.2.1
Supervisor 2024.01.1
Operating System 11.5
Frontend 20240207.1

**Version of the component**
v0.5.9

**Logging**
Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.12/site-packages/backoff/_common.py:120
First occurred: 09:46:18 (1 occurrences)
Last logged: 09:46:18

Giving up connect(...) after 11 tries (KeyError: 'refreshToken')

**Additional context**
I cannot share debug-logs because I cant get the integration to work at all anymore.

**Comment by Ton-O** [comment] 2024-02-16 14:11
I'm having similar problems. Connection fails most of the time with:
2024-02-16 14:04:39.780 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lghorizon
2024-02-16 14:05:39.865 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lghorizon
2024-02-16 14:06:39.942 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lghorizon
2024-02-16 14:07:40.020 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lghorizon
2024-02-16 14:08:40.090 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lghorizon
2024-02-16 14:08:41.951 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxx for lghorizon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
asyncio.exceptions.CancelledError: Global task timeout
2024-02-16 14:08:41.964 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 2 - moving forward
2024-02-16 14:13:44.569 ERROR (SyncWorker_6) [lghorizon.lghorizon_api] Giving up connect(...) after 11 tries (paho.mqtt.client.WebsocketConnectionError: WebSocket handshake error)

Sometimes a reboot of HA does work (for a short period).

**Comment by Ton-O** [comment] 2024-02-17 10:55
I need to add that after several restarts of HomeAssistant, the integration started working again; not sure for how long, but worth while mentioning.

**Comment by DaveCamenisch** [comment] 2024-02-18 09:31
Same problem here since a few days...

```
2024-02-18 10:23:19.143 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lghorizon
2024-02-18 10:24:19.250 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lghorizon
2024-02-18 10:25:19.369 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lghorizon
2024-02-18 10:26:19.479 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: lghorizon
2024-02-18 10:27:15.169 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 079xxxxxxx for lghorizon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
asyncio.exceptions.CancelledError: Global task timeout
2024-02-18 10:27:15.180 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 2 - moving forward

```

**Comment by filip-heens** [comment] 2024-02-18 22:53
same here, suddenly LG Horizon wouldn't start anymore when restarting .
So I eventually I removed the integration and reinstalled it.
But now it won't even log in anymore?

I'm having these errors in the  home-assistant.log (I guess that's where I have to go looking for erors? ;)
2024-02-18 23:33:22.742 ERROR (SyncWorker_12) [lghorizon.lghorizon_api] Giving up connect(...) after 11 tries (ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000))
2024-02-18 23:33:22.744 ERROR (MainThread) [custom_components.lghorizon.config_flow] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)
2024-02-18 23:36:05.421 ERROR (SyncWorker_13) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-preprod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-preprod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token)
2024-02-18 23:36:21.239 ERROR (SyncWorker_13) [lghorizon.lghorizon_api] Giving up _do_api_call(...) after 3 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-preprod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-preprod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token)
2024-02-18 23:36:21.241 ERROR (SyncWorker_13) [lghorizon.lghorizon_api] Giving up connect(...) after 11 tries (lghorizon.exceptions.LGHorizonApiConnectionError: Unable to call https://spark-preprod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token. Error:401 Client Error: Unauthorized for url: https://spark-preprod-be.gnp.cloud.telenet.tv/auth-service/v1/mqtt/token)
(I did select Telenet and not Telenet PREPROD)

Next trial
2024-02-18 23:43:32.959 ERROR (SyncWorker_8) [lghorizon.lghorizon_api] Giving up connect(...) after 11 tries (ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000))
2024-02-18 23:43:35.897 ERROR (MainThread) [frontend.js.latest.202402071] Uncaught error from Edge 121.0.0.0 on Windows 10
TypeError: Cannot read properties of undefined (reading 'domain')
_keyFunction (src/panels/config/integrations/dialog-add-integration.ts:464:16)
keyFunction (src/virtualize.ts:116:41)
r (src/directives/repeat.ts:56:28)
ct (src/directives/repeat.ts:93:52)
update (src/directive.ts:134:16)
_$AS (src/lit-html.ts:1085:23)
S (src/lit-html.ts:1362:12)
_$AI (src/async-directive.ts:366:18)
setValue (src/virtualize.ts:139:13)
dispatchEvent (src/Virtualizer.ts:808:23)
2024-02-18 23:43:39.239 ERROR (MainThread) [frontend.js.latest.202402071] Uncaught error from Edge 121.0.0.0 on Windows 10
TypeError: Cannot read properties of undefined (reading 'domain')
_keyFunction (src/panels/config/integrations/dialog-add-integration.ts:464:16)
keyFunction (src/virtualize.ts:116:41)
r (src/directives/repeat.ts:56:28)
ct (src/directives/repeat.ts:93:52)
update (src/directive.ts:134:16)
_$AS (src/lit-html.ts:1085:23)
S (src/lit-html.ts:1362:12)
_$AI (src/async-directive.ts:366:18)
setValue (src/virtualize.ts:139:13)
dispatchEvent (src/Virtualizer.ts:808:23)
2024-02-18 23:43:42.132 ERROR (MainThread) [frontend.js.latest.202402071] Uncaught error from Edge 121.0.0.0 on Windows 10
TypeError: Cannot read properties of undefined (reading 'domain')
_keyFunction (src/panels/config/integrations/dialog-add-integration.ts:464:16)
keyFunction (src/virtualize.ts:116:41)
r (src/directives/repeat.ts:56:28)
ct (src/directives/repeat.ts:93:52)
update (src/directive.ts:134:16)
_$AS (src/lit-html.ts:1085:23)
S (src/lit-html.ts:1362:12)
_$AI (src/async-directive.ts:366:18)
setValue (src/virtualize.ts:139:13)
dispatchEvent (src/Virtualizer.ts:808:23)


![image](https://github.com/Sholofly/lghorizon/assets/97739634/13745335-5dea-4802-998e-c88ea2cf9cea)

**Comment by rudi159** [comment] 2024-02-19 14:12
Hi,

I have been experiencing the same problem: since 2 days (after restarting HA due to an update) the integration cannot be loaded anymore and delays the startup of HA. (i'm using Telenet in Belgium)

This is my logfile without personal info: [lghorizon failed to setup.txt](https://github.com/Sholofly/lghorizon/files/14332082/lghorizon.failed.to.setup.txt)

Thanks in advance for looking for a cause or solution,



Rudi

**Comment by filip-heens** [comment] 2024-02-19 15:28
Issue is due to expired horizon.tv SSL certificate 😉 ☹
See issue 114 for more information
Guess we’ll have to wait ☹

**Comment by Ton-O** [comment] 2024-02-20 08:07
Issue with certificate seems to be fixed now.

**Comment by DaveCamenisch** [comment] 2024-02-20 09:12
Nope, still not working here... 🙁
I tried to reinstall the connection, but it's still the same problem:

2024-02-20 10:02:13.729 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxx for lghorizon
File "/config/custom_components/lghorizon/__init__.py", line 50, in async_setup_entry
2024-02-20 10:07:19.403 ERROR (SyncWorker_3) [lghorizon.lghorizon_api] Giving up connect(...) after 11 tries (KeyError: 'refreshToken')

**Comment by Ton-O** [comment] 2024-02-20 09:40
Sorry to hear that. I restarted HomeAssistant because [this](https://github.com/Sholofly/lghorizon/issues/114) issue was mentioned as solved. After reboot, iintegration worked again.

**Comment by steuerzentrale** [comment] 2024-02-20 19:08
I deleted the HACS-integration and re-installed it. Still got the error like @DaveCamenisch 

Logger: lghorizon.lghorizon_api
Source: /usr/local/lib/python3.12/site-packages/backoff/_common.py:120
First occurred: 19:10:58 (1 occurrences)
Last logged: 19:10:58

Giving up connect(...) after 11 tries (KeyError: 'refreshToken')

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.lghorizon.config_flow
Source: custom_components/lghorizon/config_flow.py:58
Integration: lghorizon (documentation, issues)
First occurred: 19:10:58 (1 occurrences)
Last logged: 19:10:58

'refreshToken'

**Comment by reda1978** [comment] 2024-02-22 15:42
Same issue as @steuerzentrale and @DaveCamenisch 

I guess we'll have to wait or something changed with moving to sunrise infrastructure after merger.

**Comment by scachemaille** [comment] 2024-02-27 07:24
I have the same issue.
I tried to debug [lghorizon-python](https://github.com/Sholofly/lghorizon-python) to see.. and this is the response I get  when it try to authorize in  `_authorize_default`

`{'
accessToken': 'xxxxx', 
'householdId': 'anonymous'
}`

I replaced the accessToken by xxxx ;)
There is no username or refreshToken field

**Comment by steuerzentrale** [comment] 2024-03-12 20:55
are there any updates/news on this issue?

**Comment by Ton-O** [comment] 2024-03-13 08:48
> are there any updates/news on this issue?

It has been working for me from the moment I reported it as solved. No issues anymore.

**Comment by DaveCamenisch** [comment] 2024-03-13 09:06
@Ton-O are you using the LG Horizon Integration with **UPC/Sunrise Switzerland**??
I have not been able to establish a connection for about 4 weeks. Reinstallation, restart etc. all tested without success.

**Comment by steuerzentrale** [comment] 2024-03-13 09:21
to add some context: I use UPC/Sunrise Switzerland and still experience the above mentioned issue, maybe it works fine with other providers, however UPC/Sunrise is not working anymore.

**Comment by Ton-O** [comment] 2024-03-13 11:01
> @Ton-O are you using the LG Horizon Integration with **UPC/Sunrise Switzerland**??
> 
> I have not been able to establish a connection for about 4 weeks. Reinstallation, restart etc. all tested without success.

No, using Ziggo (UPC) in the Netherlands.

**Comment by DaveCamenisch** [comment] 2024-03-13 11:05
Ok, here in Switzerland the problem is unfortunately still there... 🙁 
@Sholofly any ideas on this issue?

**Comment by reda1978** [comment] 2024-03-15 12:35
I can only confirm that now two weeks that it doesn't work anymore with UPC Switzerland.
I am still wandering if sunrise is not merging servers.

**Comment by reda1978** [comment] 2024-04-07 11:47
Hello,

Did anyone from Switzerland fix the issue with UPC ?

Removed and re-added many times, but unsuccessful to connect...

**Comment by steuerzentrale** [comment] 2024-04-08 16:33
@reda1978 No, I experience the same issue with Sunrise Switzerland which is the same as UPC. I am very happy to assist with data and testing as I dont have the knowledge to fix it.

**Comment by reda1978** [comment] 2024-04-17 07:56
@steuerzentrale I am too happy to insist but I am too not a code guy...

Anyhow, I hope it will somehow be fixed because it was so convenient when it was working

**Comment by DaveCamenisch** [comment] 2024-04-17 07:59
+1 
Yes, it would be really sad if it stopped working!   @Sholofly 🫣

**Comment by netrene** [comment] 2024-06-23 10:05
@Sholofly 
Really sad that it doesn´t work since monthes now in Switzerland. Can´t we check together how much effort it is to get it running again? Maybe just some Server adresses changed. I´m willing to help to get this fixed.
Please help.
René

**Comment by Sholofly** [comment] 2024-09-21 22:35
Hi @netrene, Have a new busy job that takes some time. I am going to pick it up soon. Please contact me on discord.

**Comment by DaveCamenisch** [comment] 2024-09-22 08:13
Let me know if there is anything I can do to help.

**Comment by Sholofly** [comment] 2024-09-22 19:36
@DaveCamenisch Can you tell me how you login on the UPC Go website (the website where you can watch television)  nowadays?

**Comment by netrene** [comment] 2024-09-22 20:03
@Sholofly 
https://www.sunrisetv.ch/de/home

https://auth.sunrise.ch/auth/realms/SRTV/protocol/openid-connect/auth?response_type=code&state=978b7dbd-4466-4e77-945c-d3938ec17838&nonce=d29b04fd-3c53-43d4-9a48-3abcc661f4b0&client_id=srtv&redirect_uri=https%3A%2F%2Fwww.sunrisetv.ch%2Fsso%2Flogin_success.html&scope=openid%20profile%20email&code_challenge=su4bnCG6wMkn13balJOFgdQmItJkVY4Zlcw-JNe6NRM&code_challenge_method=S256&request_type=code&ui_locales=de

**Comment by netrene** [comment] 2024-09-22 20:08
And when I start a movie I see this in the developer tools:
https://spark-prod-ch.gnp.cloud.sunrisetv.ch/eng/web/picker-service/v1/titleAlsoAvailableOn?profileId=xxxxxxxxx

Maybe that helps.

**Comment by Sholofly** [comment] 2024-09-22 20:17
Yes, oAuth is the issue, unortunately its impossible for me to make it work without credentials, and nearly impossible to make it work with credentials.....

**Comment by netrene** [comment] 2024-09-22 20:37
If we have no chance let´s use it. I would be willing to share my credentials.

**Comment by DaveCamenisch** [comment] 2024-09-22 21:08
The following URLs are displayed in my browser when I log in: (the parameters change each time)

https://auth.sunrise.ch/auth/realms/SRTV/login-actions/authenticate?execution=4e02268b-59d8-49d9-8baa-600bcd0fbd3b&client_id=srtv&tab_id=yQm3oZRqrak

https://auth.sunrise.ch/auth/realms/SRTV/protocol/openid-connect/auth?response_type=code&state=070f0344-0331-4d88-a4e8-9f4d3119642c&nonce=38142feb-05e4-4f93-9716-5bfea9fb1d67&client_id=srtv&redirect_uri=https%3A%2F%2Fwww.sunrisetv.ch%2Fsso%2Flogin_success.html&scope=openid%20profile%20email&code_challenge=Dvh5tjDDZKeYcM_jFLFrE3IEBCRLuosL5pWxzHEEL_E&code_challenge_method=S256&request_type=code&ui_locales=de

**Comment by Sholofly** [comment] 2024-09-23 20:00
@DaveCamenisch, can you find an URL that's using a refreshToken to retrieve an accesToken. In GB for eample there's a call to: /auth-service/v1/authorization/refresh

**Comment by DaveCamenisch** [comment] 2024-09-24 07:01
Not sure where to search but in the Safari browser sources I found this (looking for /refresh and auth-service):

_"authorizationService": {
        "URL": "https://spark-prod-ch.gnp.cloud.sunrisetv.ch/auth-service"_

The only "/refresh" I found was in a 600k large js file (main.dart.68e6b560.js):

_fG3(a, b) {
            var s,
                r,
                q,
                p
            $.e2.bE(0, B.T0, new A.de1())
            s = A.bH("/v1/authorization/refresh", 0, null)
            r = t.N
            r = A.M(r, r)
            r.A(0, "X-Device-Code", b)
            q = this.a
            q === $ && A.e()
            p = A.ce("POST", s, q.a, a, r, !1, !1, null, B.S, !1)
            r = t.qW
            return this.a.bX(0, p, r, r)
        },_

And on the login form I found this:

_https://auth.sunrise.ch/auth/realms/SRTV/login-actions/authenticate?execution=4e02268b-59d8-49d9-8baa-xxxxxxxxxx&client_id=srtv&tab_id=FUmZxxxxxx_

Maybe you can guide me to where I can find the expected URL?

**Comment by netrene** [comment] 2024-10-26 19:51
Thank you so much for the CH update. I can confirm it´s working again.

For the others take care about the described procedure to get a token.

By the way Sunrise is working now also with the email address.

Made my day
Thx René

**Comment by Sholofly** [comment] 2024-10-26 20:38
@DaveCamenisch Fixed. Notice the new configuration flow!

**Closed as completed by Sholofly** 2024-10-26 20:38 UTC
Labels: bug

**Comment by DaveCamenisch** [comment] 2024-10-26 20:55
**THANK YOU!**
It's working again 🎉🥳

**Comment by scachemaille** [comment] 2024-10-30 20:17
I don't see any tokens when connecting :(
or did I miss something?

**Comment by netrene** [comment] 2024-10-30 20:39
Not sure if you receive this answer as the ticket is closed.

Maybe worth to mention it did not work for me in Chrome. Token was always empty. I had to use firefox to get it right.

René

**Comment by Sholofly** [comment] 2024-10-31 07:18
What rene says! In the Firefox extension you should be able to retrieve the token.
